CREATE DATABASE bdmtcc;

USE bdmtcc;

CREATE TABLE Aluno (
idaluno INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(30),
email VARCHAR(20),
senha VARCHAR(8)
);

CREATE TABLE Anotacoes (
idanotacao INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
idaluno INTEGER NOT NULL,
assunto VARCHAR(20),
texto VARCHAR(1000),
FOREIGN KEY(idaluno) REFERENCES aluno (idaluno) ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE Pontuacao (
idpontuacao INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
idaluno INTEGER NOT NULL,
total INTEGER NOT NULL,
erro INTEGER NOT NULL,
acerto INTEGER NOT NULL,
FOREIGN KEY(idaluno) REFERENCES aluno(idaluno) ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE Cronometro (
idcronometro INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
idaluno INTEGER NOT NULL,
tempomensal VARCHAR(5) NOT NULL,
temposemanal VARCHAR(6) NOT NULL,
tempo VARCHAR(10) NOT NULL,
FOREIGN KEY(idaluno) REFERENCES aluno(idaluno) ON DELETE CASCADE
)ENGINE=INNODB;