/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastro;




import Cadastro.PrincipalPage;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;
import com.mysql.cj.xdevapi.Session;
import com.sun.jdi.connect.spi.Connection;
import controller.conUsuario;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.classUsuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;





public class pomodoro_view extends javax.swing.JFrame {
    
classUsuario usuarioLogado = classUsuario.Session.getUsuarioLogado();
conUsuario con = new conUsuario();
classUsuario tempo = new classUsuario();
    private int minutes = 0;
    private int seconds = 0;
    private int totalSeconds = minutes * 60 + seconds + 1;
    private int count = totalSeconds;
    private Timer timer;
    private int iniTimeMinutes = 0;
    private int iniTimeSeconds = 0;
    
    
        
    
    public pomodoro_view() {
        dispose();
        initComponents();
        this.setLocationRelativeTo(null);//fazer a janela aparecer logo no centro da tela quando criada
        
        
        timer = new Timer();
        timeText.setText(String.format("%02d:%02d", minutes, seconds));
        
        
        
        
    }
    
    public static void main(String[] args)throws Exception{

     
        
    new pomodoro_view().setVisible(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeText = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        textSession = new javax.swing.JLabel();
        tztVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeText.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        timeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeText.setText("00:00");
        timeText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        timeText.setAlignmentY(0.6F);
        jPanel1.add(timeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 130, 50));

        start.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 130, 50));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton2.setText("+5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 90, 30));

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("-5");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 80, 30));

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton4.setText("Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 130, 50));

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton5.setText("Resetar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 50));

        textSession.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        textSession.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(textSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 400, 40));

        tztVoltar.setText("Voltar");
        tztVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tztVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(tztVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
  FlatNightOwlIJTheme.setup();
        if(minutes > 0){
        iniTimeMinutes = minutes;
        iniTimeSeconds = seconds;
        textSession.setText("");
        
        timer = new Timer();
        TimerTask task;
        task = new TimerTask() {
            @Override
            public void run() {
                count --;
                
                if(count >= 0){
                    int remainningMinutes = count/60;
                    int remainningSeconds = count%60;
                    timeText.setText(String.format("%02d:%02d", remainningMinutes, remainningSeconds));
                    
                    if(count == 0){
                      textSession.setText(String.format("Parabéns, você concluiu sua sessão! \nTempo total: %02d:%02d", iniTimeMinutes, iniTimeSeconds));
                      
                     int tempot=usuarioLogado.getTempo();
                     int tempt = tempot+iniTimeMinutes; 
                     
                     
                      
                      tempo.setTempo(tempt);
                        try {
                            con.attTempo(tempo);
                        } catch (SQLException ex) {
                            Logger.getLogger(pomodoro_view.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                }else{
                    timer.cancel();
                    minutes = 0;
                    seconds = 0;
                    JOptionPane.showMessageDialog(null, "Sua sessão acabou!");
                    
                }
                
            }
        };
        
        timer.scheduleAtFixedRate(task, 1, 1000);//se quiser testar mais rapido altera o valor 1000 para 1
                
        
        }else{
            JOptionPane.showMessageDialog(null, "Aumente o tempo no relógio para iniciar");
        }
        
     
        
    }//GEN-LAST:event_startActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       minutes += 5;
       timeText.setText(String.format("%02d:%02d", minutes, seconds));
      totalSeconds = minutes * 60 + seconds + 1;
      count = totalSeconds;
      timer.cancel();
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(minutes > 0){
        minutes -= 5;
       timeText.setText(String.format("%02d:%02d", minutes, seconds));
       totalSeconds = minutes * 60 + seconds + 1;
      count = totalSeconds;
      timer.cancel();
      
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       timer.cancel();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       timer.cancel();
       minutes = 0;
       seconds = 0;
       timeText.setText(String.format("%02d:%02d", minutes, seconds));
       textSession.setText("");
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tztVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tztVoltarActionPerformed
        PrincipalPage page = new PrincipalPage();
        page.setVisible(true);
         this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_tztVoltarActionPerformed

  
    /**
     * @param args the command line arguments
     */
   
    
    //public static void main(String args[]){
        
        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
           //     new pomodoro_view().setVisible(true);
          //  }
       // });
        
        
        
         
        
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton start;
    private javax.swing.JLabel textSession;
    private javax.swing.JLabel timeText;
    private javax.swing.JButton tztVoltar;
    // End of variables declaration//GEN-END:variables
}
